<a href="https://colab.research.google.com/github/aroy1856/mlproject/blob/main/00_tesdsorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.18.0


In [ ]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
scaler.ndim

0

In [ ]:
vector.ndim

1

In [ ]:
# load data from sample_data folder
!ls sample_data/


anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
read = tf.io.read_file('sample_data/anscombe.json')

In [ ]:
import pandas as pd
df = pd.read_csv('sample_data/california_housing_train.csv')

In [ ]:
df2 = pd.read_json('sample_data/anscombe.json')

In [ ]:
df2

Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
read

<tf.Tensor: shape=(), dtype=string, numpy=b'[\n  {"Series":"I", "X":10.0, "Y":8.04},\n  {"Series":"I", "X":8.0, "Y":6.95},\n  {"Series":"I", "X":13.0, "Y":7.58},\n  {"Series":"I", "X":9.0, "Y":8.81},\n  {"Series":"I", "X":11.0, "Y":8.33},\n  {"Series":"I", "X":14.0, "Y":9.96},\n  {"Series":"I", "X":6.0, "Y":7.24},\n  {"Series":"I", "X":4.0, "Y":4.26},\n  {"Series":"I", "X":12.0, "Y":10.84},\n  {"Series":"I", "X":7.0, "Y":4.81},\n  {"Series":"I", "X":5.0, "Y":5.68},\n\n  {"Series":"II", "X":10.0, "Y":9.14},\n  {"Series":"II", "X":8.0, "Y":8.14},\n  {"Series":"II", "X":13.0, "Y":8.74},\n  {"Series":"II", "X":9.0, "Y":8.77},\n  {"Series":"II", "X":11.0, "Y":9.26},\n  {"Series":"II", "X":14.0, "Y":8.10},\n  {"Series":"II", "X":6.0, "Y":6.13},\n  {"Series":"II", "X":4.0, "Y":3.10},\n  {"Series":"II", "X":12.0, "Y":9.13},\n  {"Series":"II", "X":7.0, "Y":7.26},\n  {"Series":"II", "X":5.0, "Y":4.74},\n\n  {"Series":"III", "X":10.0, "Y":7.46},\n  {"Series":"III", "X":8.0, "Y":6.77},\n  {"Series